### ISSUE TITLE
How can I download the characterdata overall rather than one by one

### ISSUE THREAD

**Issue by hxhxzd** [SilentNightSound/GI-Model-Importer-Assets#2]
How can I download the characterdata overall rather than one by one，I can only click to download one file once

**Comment by SilentNightSound** [comment]
You can either click the green code button Code->Download zip, or use the "git clone" command on the repo to get all the data at once

**Comment by hxhxzd** [comment]
I'm so sorry about that. But I still can't find the green button to download. Can you say it in more detail？ Thanks a lot.

**Comment by SilentNightSound** [comment]
![image](https://user-images.githubusercontent.com/107697535/180660497-bbfa59c7-ce4f-4cad-86af-b9e5d1afb3c2.png)

**Comment by hxhxzd** [comment]
ohh！thank u！

**Comment by SilentNightSound** [comment]
no problem!
