### ISSUE TITLE
Archaic Prototype Claymore dump is not importing in Blender

### ISSUE THREAD

**Issue by toto621-linux** [SilentNightSound/GI-Model-Importer-Assets#22]
Do not import at all in blender (see screenshot of error output) : https://i.imgur.com/WIqqHzB.jpeg

Newer dumps like Sapwood blade work without issues (made as test)

**Comment by lastlament** [comment]
I updated the dump as there were a few issues with the hashes, let me know if it works now.

**Comment by toto621-linux** [comment]
It's ok, issue fixed :)
