### ISSUE TITLE
Blender went wrong

### ISSUE THREAD

**Issue by hxhxzd** [SilentNightSound/GI-Model-Importer-Assets#3]
![-4ea086caa021e888](https://user-images.githubusercontent.com/109600477/180757368-e12d2c39-e405-45c3-8924-20d4c49774ff.png)
I already rename the file and change another MOD， it still went wrong

**Comment by gawgua** [comment]
> name 'sys' is not defined

try install python

**Comment by SilentNightSound** [comment]
This was a glitch in the previous version of the blender plugin, has been fixed. Closing issue
